### ISSUE TITLE
Failure to compile with gcc 4.8

### ISSUE THREAD

**Issue by jgornowich** [oliora/ppconsul#37]
The most recent additions for supporting sessions management causes a failure to build under gcc 4.8 with the following output.

```
sessions.h:61:21: error: default argument missing for parameter 5 of ‘std::string ppconsul::sessions::Sessions::create(const string&, std::chrono::seconds, ppconsul::sessions::InvalidationBehavior, std::chrono::seconds, const Params& ...)’
         std::string create(const std::string &node = "",
```

I have been using ppconsul for a while now in a project, but I not currently able to upgrade the compiler that is being used.  Is it a problem to just remove the default arguments to the `create` method

**Comment by oliora** [comment]
It’s fine as a temporary workaround. The correct solution would be make a keyword for every optional parameters so session can be created like `create(kw::lock_time = std::chrono::seconds(5), ...)`.

**Comment by oliora** [comment]
I’ll make a proper fix for this today

**Comment by bkannadassan** [comment]
Even me facing the same issue, I have removed the default value for now. Is it ok to keep it without default values ?. Btw I am setting "BUILD_STATIC_LIB" to ON in cmake is there any issue if I do the same ?, My OS is  centos.

**Comment by oliora** [comment]
@bkannadassan static lib should work fine. Please file an issue if you face any problems with it.

**Comment by oliora** [comment]
Should work for now. Please reopen if it's not fixed.

**Comment by jgornowich** [comment]
@oliora Great, I will test this out tonight and let you know

**Comment by jgornowich** [comment]
I have tested this out and everything appears to work.  thx
